theme: cinder

site_name: Bullet Docs
site_description: The full documentation for Bullet - A Real Time Data Query Engine
site_author: Akshai Sarma
site_url: https://bullet-db.github.io/
repo_url: https://github.com/bullet-db

pages:
- Home: index.md
- Quick Start:
  - Spark: quick-start/spark.md
  - Storm: quick-start/storm.md
- Backend:
  - Data Ingestion:
    - Record Container: backend/ingestion.md
    - DSL: backend/dsl.md
  - Storm:
    - Architecture: backend/storm-architecture.md
    - Setup: backend/storm-setup.md
    - Performance: backend/storm-performance.md
  - Spark:
    - Architecture: backend/spark-architecture.md
    - Setup: backend/spark-setup.md
    - Performance: backend/spark-performance.md
- PubSub:
  - Architecture: pubsub/architecture.md
  - Kafka: pubsub/kafka.md
  - REST: pubsub/rest.md
  - Pulsar: pubsub/pulsar.md
  - Storm DRPC: pubsub/storm-drpc.md
- Web Service:
  - Setup: ws/setup.md
  - API:
    - BQL: ws/api-bql.md
    - JSON: ws/api-json.md
  - Query Examples: ws/examples.md
- UI:
  - Setup: ui/setup.md
  - Usage: ui/usage.md
- Releases: releases.md
- About:
  - Contributing: about/contributing.md
  - Contact Us: about/contact.md

markdown_extensions:
    - admonition
    - attr_list

extra:
  collapse_toc: true
  include_search: true
  service_version: v0.6.1

extra_css:
  - css/extra.css

copyright: "Bullet is licensed under the <a href='https://github.com/bullet-db/bullet-core/blob/master/LICENSE'>Apache 2 license</a>."
