theme: cinder

site_name: Bullet Docs
site_description: The full documentation for Bullet - A Real Time Data Query Engine
site_author: Akshai Sarma
site_url: https://yahoo.github.io/bullet-docs
site_favicon: img/favicon.ico
repo_name: yahoo/bullet-core

pages:
- Home: index.md
- Quick Start: quick-start.md
- Backend:
  - Getting your data into Bullet: backend/ingestion.md
  - Storm:
    - Architecture: backend/storm-architecture.md
    - Setup: backend/storm-setup.md
    - Performance: backend/storm-performance.md
- PubSub:
  - Architecture: pubsub/architecture.md
  - Kafka: pubsub/kafka.md
  - Storm DRPC: pubsub/storm-drpc.md
- Web Service:
  - Setup: ws/setup.md
  - API: ws/api.md
  - Examples: ws/examples.md
- UI:
  - Setup: ui/setup.md
  - Usage: ui/usage.md
- Releases: releases.md
- About:
  - Contributing: about/contributing.md
  - Contact Us: about/contact.md

markdown_extensions:
    - admonition

extra:
  collapse_toc: true
  include_search: true
  service_version: v0.4.0

extra_css:
  - css/extra.css

copyright: "Bullet is licensed under the <a href='https://github.com/yahoo/bullet/blob/master/LICENSE'>Apache 2 license"
